encoder:
  n_enc_channels: 128    # origin: 192
  filter_channels: 128   # origin: 768
  filter_channels_dp: 128  # origin: 256
  n_enc_layers: 2
  enc_kernel: 3
  enc_dropout: 0.1
  n_heads: 2
  window_size: 4
  length_scale: 1.0 # speech pace

decoder:
  dec_dim: 64
  beta_min: 0.05
  beta_max: 20.0
  pe_scale: 1000  # 1 for `grad-tts-old.pt` checkpoint
  stoc: True
  temperature: 1.0 # terminal variance
  n_timesteps: 50

unet:
  unet_type: "origin"  # origin or diffuser
  att_type: "linear"   # linear or crossAtt

spk_emb_dim: 64
emo_emb_dim: 5

mu: "txt_depend"         # txt_depend or norm
solver: "sde"            # sde or ode

# -----------------------not used-------------

vocoder:
  model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "LJSpeech" # support  'LJSpeech', 'universal'

variance_predictor:
  filter_size: 256
  kernel_size: 3
  dropout: 0.5

style_emb:
  fusion_style: "crossAttention"  # support "add" or "crossAttention"
  exist: True
  dims: 768

CrossAttention:
  txt_dim: 256
  nhead: 8
  dropout: 0.2
  style_dim: 256

model_name: "FastSpeech2_iiv"  # support FastSpeech2 and FastSpeech2_iiv


variance_embedding:
  pitch_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the pitch values are not normalized during preprocessing
  energy_quantization: "linear" # support 'linear' or 'log', 'log' is allowed only if the energy values are not normalized during preprocessing
  n_bins: 256

# gst:
#   use_gst: False
#   conv_filters: [32, 32, 64, 64, 128, 128]
#   gru_hidden: 128
#   token_size: 128
#   n_style_token: 10
#   attn_head: 4

multi_speaker: True

max_seq_len: 1000

vocoder:
  model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "LJSpeech" # support  'LJSpeech', 'universal'

iiv_model: "conv2d"
