path:
  ckpt_path: "./output/ckpt/ESD"
  # interpEmoTTS_frame2frameAttn, interpEmoTTS_linearAttn, interpEmoTTS_frame2frameAttn_noJoint
  log_dir: "./logs/interpEmoTTS_frame2frameAttn_noJoint/" # for training
  result_path: "./output/result/ESD"
# train
n_epochs: 1000
resume_epoch: 0
batch_size: 48
learning_rate: 1e-4
seed: 37

# evaluation:
# 1. save gd/enc/dec/align images of each test in logger
# 2. do 1 in plot and synthesize speech of each test for show_img_per_epoch (=5) a time, and first 3 epoch
# 3. save in every epoch
test_size: 3


# save model
save_every: 1

# ---------------not used-------------
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 100
  val_step: 100
  save_step: 3000



# log_dir
# gradtts_crossSelf_puncond_n1_neworder_fixmask:
# interpEmoTTS_frame2frameAttn: frame to frame attention