path:
  ckpt_path: "./output/ckpt/ESD"
  log_dir: "./logs/gradtts_crossSelf_puncond_n1_neworder_fixmask/" # for training
  result_path: "./output/result/ESD"
test_size: 4
n_epochs: 10000
batch_size: 48
learning_rate: 1e-4
seed: 37
save_every: 1
resume_epoch: 40

# ---------------not used-------------
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 100
  val_step: 100
  save_step: 3000